export enum CoinTypes {
    COINS = "coins",
    GGG = "ggg_coins",
    EFROGS = "efrogs_coins",
    UNFETCHERED = "unfetchered_coins",
    DMAIL = "dmail_coins",
    IMTOKEN = "imtoken_coins",
    NOTWIFGARY = "notwifgary_coins",
    METAVERSEPOST = "metaversepost_coins",
    MEMEFI = "memefi_coins",
    LCOINS = "l_coins",
    XCOINS = "x_coins",
    TOWNSTORY_BADGE = "townstory_badge",
    WOLFSWAP_BADGE = "wolfswap_badge",
    DROPLINKED_BADGE = "droplinked_badge",
    OMNISEA_BADGE = "omnisea_badge",
    TASKON_BADGE = "taskon_badge",
    PLENA_FINANCE_BADGE = "plena_finance_badge",
    OPENOCEAN_BADGE = "openocean_badge",
    OKX_WEB3_BADGE = "okx_web3_badge",
    DEVOMON_BADGE = "devomon_badge",
    CHAIN_CATCHE_BADGE = "chain_catche_badge",
    
    //Week #3
    VELOCORE_BADGE = "velocore_badge",
    FOX_WALLET_BADGE = "fox_wallet_badge",
    PHEASANT_BRIDGE_BADGE = "pheasant_bridge_badge",
    COINEASY_BADGE = "coineasy_badge",
    LINUS_BADGE = "linus_badge",
    SWING_BADGE = "swing_badge",
    FROGWIFCAT_BADGE = "frogwifcat_badge",
    MENDI_FINANCE_BADGE = "mendi_finance_badge",
    ROBOHERO_BADGE = "robohero_badge",
    INTRACT_BADGE = "intract_badge",
    FORESIGHT_NEWS_BADGE = "foresight_news_badge",

    // Week#4
    YGG_JAPAN_BADGE = "ygg_japan_badge",
    BILINEAR_BADGE = "bilinear_badge",
    OKAPI_BADGE = "okapi_badge",
    CYVERS_BADGE = "cyvers_badge",
    DEGUARD_BADGE = "deguard_badge",
    MC2_FINANCE_BADGE = "mc2_finance_badge",
    IQ_PROTOCOL_BADGE = "iq_protocol_badge",
    MICRO3_BADGE = "micro3_badge",
    GAMEX_BADGE = "gamex_badge",
    LADDER_BADGE = "ladder_badge",
    SCHRODINGER_S_CAT_BADGE = "schrodinger_s_cat_badge",
    JUMPER_EXCHANGE_BADGE = "jumper_exchange_badge"
}
