import { CoinTypes } from "./coins.enum";

export const coinsMap = [
    {
        image: "/l_coin.png",
        name: "Linea badge",
        type: CoinTypes.LCOINS,
        tokenId: 0,
        isActive: true,
    },
    {
        image: "/x_coin.png",
        name: "Lynex badge",
        type: CoinTypes.XCOINS,
        tokenId: 1,
        isActive: true,
    },
    {
        image: "/memeFi.png",
        name: "MemeFi badge",
        type: CoinTypes.MEMEFI,
        tokenId: 2,
        isActive: true,
    },
    {
        image: "/ggg.png",
        name: "GGG badge",
        type: CoinTypes.GGG,
        tokenId: 3,
        isActive: true,
    },
    {
        image: "/efrogs.png",
        name: "Efrogs badge",
        type: CoinTypes.EFROGS,
        tokenId: 4,
        isActive: true,
    },
    {
        image: "/theUnfetchered.png",
        name: "The Unfetchered badge",
        type: CoinTypes.UNFETCHERED,
        tokenId: 5,
        isActive: true,
    },
    {
        image: "/dmail.png",
        name: "Dmail badge",
        type: CoinTypes.DMAIL,
        tokenId: 6,
        isActive: true,
    },
    {
        image: "/imToken.png",
        name: "ImToken badge",
        type: CoinTypes.IMTOKEN,
        tokenId: 7,
        isActive: true,
    },
    {
        image: "/notWifGary.png",
        name: "NotWifGary badge",
        type: CoinTypes.NOTWIFGARY,
        tokenId: 8,
        isActive: true,
    },
    {
        image: "/metaversePost.png",
        name: "MPost badge",
        type: CoinTypes.METAVERSEPOST,
        tokenId: 9,
        isActive: true,
    },
    {
        image: "/townstory.png",
        name: "TownStory badge",
        type: CoinTypes.TOWNSTORY_BADGE,
        tokenId: 10,
        isActive: true,
    },
    {
        image: "/wolfswap.png",
        name: "WolfSwap badge",
        type: CoinTypes.WOLFSWAP_BADGE,
        tokenId: 11,
        isActive: true,
    },
    {
        image: "/droplinked.png",
        name: "Droplinked badge",
        type: CoinTypes.DROPLINKED_BADGE,
        tokenId: 12,
        isActive: true,
    },
    {
        image: "/omnisea.png",
        name: "OmniSea badge",
        type: CoinTypes.OMNISEA_BADGE,
        tokenId: 13,
        isActive: true,
    },
    {
        image: "/taskon.png",
        name: "TaskOn badge",
        type: CoinTypes.TASKON_BADGE,
        tokenId: 14,
        isActive: true,
    },
    {
        image: "/plena_finance.png",
        name: "Plena Finance badge",
        type: CoinTypes.PLENA_FINANCE_BADGE,
        tokenId: 15,
        isActive: true,
    },
    {
        image: "/openocean.png",
        name: "OpenOcean badge",
        type: CoinTypes.OPENOCEAN_BADGE,
        tokenId: 16,
        isActive: true,
    },
    {
        image: "/okx_web3.png",
        name: "OKX Web3 badge",
        type: CoinTypes.OKX_WEB3_BADGE,
        tokenId: 17,
        isActive: true,
    },
    {
        image: "/devomon.png",
        name: "Devomon badge",
        type: CoinTypes.DEVOMON_BADGE,
        tokenId: 18,
        isActive: true,
    },
    {
        image: "/chain_catche.png",
        name: "Chain Catche badge",
        type: CoinTypes.CHAIN_CATCHE_BADGE,
        tokenId: 19,
        isActive: true,
    },
    // Week #3
    {
        image: "/su_velocore.png",
        name: "Velocore badge",
        type: CoinTypes.VELOCORE_BADGE,
        tokenId: 20,
        isActive: true,
    },
    {
        image: "/su_fox_wallet.png",
        name: "Fox Wallet badge",
        type: CoinTypes.FOX_WALLET_BADGE,
        tokenId: 21,
        isActive: true,
    },
    {
        image: "/su_pheasant_bridge.png",
        name: "Pheasant Bridge badge",
        type: CoinTypes.PHEASANT_BRIDGE_BADGE,
        tokenId: 22,
        isActive: true,
    },
    {
        image: "/su_coineasy.png",
        name: "CoinEasy badge",
        type: CoinTypes.COINEASY_BADGE,
        tokenId: 23,
        isActive: true,
    },
    {
        image: "/su_linus.png",
        name: "Linus badge",
        type: CoinTypes.LINUS_BADGE,
        tokenId: 24,
        isActive: true,
    },
    {
        image: "/su_swing.png",
        name: "Swing badge",
        type: CoinTypes.SWING_BADGE,
        tokenId: 25,
        isActive: true,
    },
    {
        image: "/su_frogwifcat.png",
        name: "FrogWifCat badge",
        type: CoinTypes.FROGWIFCAT_BADGE,
        tokenId: 26,
        isActive: true,
    },
    {
        image: "/su_mendi_finance.png",
        name: "Mendi Finance badge",
        type: CoinTypes.MENDI_FINANCE_BADGE,
        tokenId: 27,
        isActive: true,
    },
    {
        image: "/su_robohero.png",
        name: "Robohero badge",
        type: CoinTypes.ROBOHERO_BADGE,
        tokenId: 28,
        isActive: true,
    },
    {
        image: "/su_intract.png",
        name: "Intract badge",
        type: CoinTypes.INTRACT_BADGE,
        tokenId: 29,
        isActive: true,
    },
    {
        image: "/su_foresight_news.png",
        name: "Foresight News badge",
        type: CoinTypes.FORESIGHT_NEWS_BADGE,
        tokenId: 30,
        isActive: true,
    },

    // Week #4
    {
        image: "/su_ygg_japan.png",
        name: "YGG Japan badge",
        type: CoinTypes.YGG_JAPAN_BADGE,
        tokenId: 31,
        isActive: true,
    },
    {
        image: "/su_bilinear.png",
        name: "Bilinear badge",
        type: CoinTypes.BILINEAR_BADGE,
        tokenId: 32,
        isActive: true,
    },
    {
        image: "/su_okapi.png",
        name: "Okapi badge",
        type: CoinTypes.OKAPI_BADGE,
        tokenId: 33,
        isActive: true,
    },
    {
        image: "/su_cyvers.png",
        name: "Cyvers badge",
        type: CoinTypes.CYVERS_BADGE,
        tokenId: 34,
        isActive: true,
    },
    {
        image: "/su_deguard.png",
        name: "DeGuard badge",
        type: CoinTypes.DEGUARD_BADGE,
        tokenId: 35,
        isActive: true,
    },
    {
        image: "/su_mc2_finance.png",
        name: "MC2 Finance badge",
        type: CoinTypes.MC2_FINANCE_BADGE,
        tokenId: 36,
        isActive: true,
    },
    {
        image: "/su_iq_protocol.png",
        name: "IQ Protocol badge",
        type: CoinTypes.IQ_PROTOCOL_BADGE,
        tokenId: 37,
        isActive: true,
    },
    {
        image: "/su_micro3.png",
        name: "Micro3 badge",
        type: CoinTypes.MICRO3_BADGE,
        tokenId: 38,
        isActive: true,
    },
    {
        image: "/su_gamex.png",
        name: "GameX badge",
        type: CoinTypes.GAMEX_BADGE,
        tokenId: 39,
        isActive: true,
    },
    {
        image: "/su_ladder.png",
        name: "Ladder badge",
        type: CoinTypes.LADDER_BADGE,
        tokenId: 40,
        isActive: true,
    },
    {
        image: "/su_schrodinger_s_cat.png",
        name: "Schrodinger's cat badge",
        type: CoinTypes.SCHRODINGER_S_CAT_BADGE,
        tokenId: 41,
        isActive: true,
    },
    {
        image: "/su_jumper_exchange.png",
        name: "Jumper Exchange badge",
        type: CoinTypes.JUMPER_EXCHANGE_BADGE,
        tokenId: 42,
        isActive: true,
    }
];